---
variables:
  CI_LOOP: verify
  CLEAN_DIB_IMAGES: 'true'
  DEPLOY_SCENARIO: k8-nosdn-nofeature
  DISTRO: ubuntu
  WORKSPACE: $CI_PROJECT_DIR
  GERRIT_CHANGE_NUMBER: $CI_PIPELINE_ID
  GERRIT_PROJECT: releng-xci
  INSTALLER_TYPE: kubespray
  XCI_FLAVOR: mini
  XCI_SCRIPTS: https://raw.githubusercontent.com/opnfv/releng/master/jjb/xci

before_script:
  - |
    if [[ ! -e ${HOME}/.ssh/id_rsa ]]; then
      ssh-keygen -q -P '' -f ${HOME}/.ssh/id_rsa
    fi
  - curl -L $XCI_SCRIPTS/xci-cleanup.sh | bash

after_script:
  - curl -L $XCI_SCRIPTS/xci-cleanup.sh | bash

xci-verify.ubuntu.virtual.master:
  tags:
    - virtual
  script:
    - curl -L $XCI_SCRIPTS/xci-set-scenario.sh | bash
    - curl -L $XCI_SCRIPTS/xci-start-new-vm.sh | bash
    - curl -L $XCI_SCRIPTS/xci-start-deployment.sh | bash
